# Generated by Django 6.0.3 on 2026-05-09 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo', '0003_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conteo', models.CharField(max_length=100, unique=True, verbose_name='Código de conteo')),
                ('fecha_conteo', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo físico',
                'verbose_name_plural': 'Conteos físicos',
                'ordering': ['-fecha_conteo'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=100, verbose_name='Código de lote')),
                ('cantidad_inicial', models.PositiveIntegerField(default=0)),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Catalogo.product')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_ingreso'],
                'unique_together': {('codigo_lote', 'product')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada - Compra a proveedor'), ('entrada_devolucion', 'Entrada - Devolución de cliente'), ('entrada_ajuste', 'Entrada - Ajuste de inventario'), ('salida_venta', 'Salida - Venta'), ('salida_devolucion_proveedor', 'Salida - Devolución a proveedor'), ('salida_merma', 'Salida - Merma/Pérdida'), ('salida_ajuste', 'Salida - Ajuste de inventario')], max_length=30, verbose_name='Tipo de movimiento')),
                ('referencia_tipo', models.CharField(choices=[('pedido', 'Pedido'), ('proveedor', 'Proveedor'), ('conteo', 'Conteo físico'), ('manual', 'Manual/Ajuste')], default='manual', max_length=20, verbose_name='Tipo de referencia')),
                ('referencia_id', models.CharField(blank=True, max_length=100, verbose_name='ID de referencia')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (positiva=entrada, negativa=salida)')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock antes del movimiento')),
                ('stock_posterior', models.PositiveIntegerField(verbose_name='Stock después del movimiento')),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Catalogo.product')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UnidadIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=100, unique=True, verbose_name='Código interno')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('merma', 'Merma/Pérdida'), ('en_reparacion', 'En reparación')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='inventario.lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_individuales', to='Catalogo.product')),
            ],
            options={
                'verbose_name': 'Unidad individual',
                'verbose_name_plural': 'Unidades individuales',
                'ordering': ['codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True)),
                ('ultima_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='Catalogo.product')),
            ],
            options={
                'verbose_name': 'Alerta de stock',
                'verbose_name_plural': 'Alertas de stock',
                'unique_together': {('product',)},
            },
        ),
        migrations.CreateModel(
            name='ConteoFisicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.PositiveIntegerField(verbose_name='Stock según sistema')),
                ('stock_contado', models.PositiveIntegerField(verbose_name='Stock contado físicamente')),
                ('diferencia', models.IntegerField(editable=False, verbose_name='Diferencia')),
                ('notas', models.TextField(blank=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.conteofisico')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.product')),
            ],
            options={
                'verbose_name': 'Item de conteo',
                'verbose_name_plural': 'Items de conteo',
                'unique_together': {('conteo', 'product')},
            },
        ),
    ]
