# Generated by Django 6.0.3 on 2026-04-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='pedidos/documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
