# Generated by Django 6.0.3 on 2026-04-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidodocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_flete_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pedidos/flete/%Y/%m/%d/'),
        ),
    ]
