# Generated by Django 5.2.8 on 2026-02-16 03:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('primer_nombre', models.CharField(help_text='Primer nombre del usuario', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, help_text='Segundo nombre del usuario (opcional)', max_length=100)),
                ('primer_apellido', models.CharField(help_text='Primer apellido del usuario', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, help_text='Segundo apellido del usuario (opcional)', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil')], help_text='Tipo de documento de identidad', max_length=2)),
                ('numero_documento', models.CharField(help_text='Número de documento (único en el sistema)', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Email único para recuperación de cuenta', max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default='estudiante', help_text='Rol del usuario en el sistema', max_length=10)),
                ('intentos_fallidos', models.IntegerField(default=0, help_text='Contador de intentos fallidos de login', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta está activa o bloqueada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['primer_nombre', 'primer_apellido'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(help_text='Especialidad o materia principal que enseña', max_length=200)),
                ('telefono_institucional', models.CharField(blank=True, help_text='Teléfono de contacto institucional', max_length=20)),
                ('firma_digital_url', models.URLField(blank=True, help_text='URL de la firma digital para oficialización de boletines PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al perfil de docente', limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['usuario__primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiantil', models.CharField(help_text='Código único del estudiante', max_length=20, unique=True)),
                ('grado_actual', models.CharField(help_text='Grado actual (ej. 11-01, 10-02)', max_length=10)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del estudiante')),
                ('nombre_acudiente', models.CharField(help_text='Nombre del acudiente o tutor', max_length=200)),
                ('telefono_acudiente', models.CharField(help_text='Teléfono de contacto del acudiente', max_length=20)),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0.0, help_text='Promedio general del estudiante (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('estado_final', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado')], default='pendiente', help_text='Estado final del periodo académico', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al perfil de estudiante', limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['grado_actual', 'usuario__primer_apellido'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['numero_documento'], name='usuarios_us_numero__b22c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_us_email_41a027_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_us_rol_1f6a22_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['codigo_estudiantil'], name='usuarios_es_codigo__1c9d52_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['grado_actual'], name='usuarios_es_grado_a_a91516_idx'),
        ),
    ]
