# Generated by Django 5.2.8 on 2026-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Obliga al usuario a cambiar la contraseña en el primer inicio de sesión'),
        ),
    ]
