# Generated by Django 5.2.8 on 2026-02-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del estudiante', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_acudiente',
            field=models.CharField(blank=True, help_text='Nombre del acudiente o tutor', max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_acudiente',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del acudiente', max_length=20),
        ),
    ]
