# Generated by Django 5.2.8 on 2026-02-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora hasta la cual la cuenta está bloqueada por intentos fallidos', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa o bloqueada permanentemente'),
        ),
    ]
