# Generated by Django 6.0.2 on 2026-02-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_bloqueado_hasta_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['usuario__primer_apellido', 'usuario__primer_nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveIndex(
            model_name='estudiante',
            name='usuarios_es_grado_a_a91516_idx',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado_actual',
        ),
    ]
