# Generated by Django 6.0.3 on 2026-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_docente_firma_digital_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
        migrations.RemoveIndex(
            model_name='estudiante',
            name='usuarios_es_codigo__1c9d52_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_us_numero__b22c5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_us_email_41a027_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_us_rol_1f6a22_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], default='buyer', max_length=10),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bloqueado_hasta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='intentos_fallidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='must_change_password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
