# Generated by Django 6.0.3 on 2026-03-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_emailchangetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Principal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='referencias_direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Referencias/Indicaciones'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Personal'),
        ),
    ]
