# Generated by Django 6.0.3 on 2026-03-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_direccion_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Usuario normal'), ('admin', 'Administrador')], default='comprador', max_length=10),
        ),
    ]
