# Generated by Django 6.0.3 on 2026-05-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token de Recuperación de Contraseña', 'verbose_name_plural': 'Tokens de Recuperación de Contraseña'},
        ),
    ]
